# This file describes the GitHub Actions workflow for continuous integration of rocket-chip.
#
# See
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# for API reference documentation on this file format.

name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  check-wit:
    name: Check Wit Manifest
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - run: ci-tests/check_submodules


  prepare-riscv-tools-cache:
    name: Prepare riscv-tools Cache
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - id: cache
        # We use an unreleased version of the cache action that adds support for
        # multiple paths to cache. This can be changed to a normal version
        # number (likely v2) once it is released. See
        # https://github.com/actions/cache/pull/212
        uses: actions/cache@9ab95382c899bf0953a0c6c1374373fc40456ffe
        with:
          path: |
            ./regression/install
            ./regression/stamps/rocket-tools_checkout.stamp
          key: riscv-tools-${{ hashFiles('./riscv-tools.hash') }}-v1

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y \
            autoconf \
            automake \
            autotools-dev \
            bison \
            build-essential \
            device-tree-compiler \
            flex \
            g++-4.8 \
            gawk \
            gcc-4.8 \
            gperf \
            libgmp-dev \
            libmpc-dev \
            libmpfr-dev \
            libusb-1.0-0-dev \
            texinfo

      - if: steps.cache.outputs.cache-hit != 'true'
        env:
          CXX: g++-4.8
          CC: gcc-4.8
        run: make tools -C regression SUITE=none


  prepare-verilator-cache:
    name: Prepare Verilator Cache
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

        # TODO: Use v2 once it is released. See the first occurrance of
        # actions/cache in this file for more details.
      - uses: actions/cache@9ab95382c899bf0953a0c6c1374373fc40456ffe
        with:
          path: ./emulator/verilator
          key: verilator-${{ hashFiles('./verilator.hash') }}-v1

      # WARNING: The version of gcc used to compile Verilator MUST match the
      # version of gcc used to compile the fesvr. There is some bug related to
      # some C struct not being ABI-compatible across gcc 4 and 5, which we have
      # not debugged yet.
      - name: Install Dependencies
        run: sudo apt-get install -y autoconf bison flex g++-4.8 gcc-4.8

      - env:
          CXX: g++-4.8
          CC: gcc-4.8
        run: make verilator -C regression SUITE=none


  check-wake-compilation:
    name: Check Wake Compilation
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Use SBT Cache
        # TODO: Use v2 once it is released. See the first occurrance of
        # actions/cache in this file for more details.
        uses: actions/cache@9ab95382c899bf0953a0c6c1374373fc40456ffe
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}-v1

      - run: ci-tests/wake_scala_compilation

  # This job is defined as a matrix job, where the definitions of each test
  # bucket is located in a shell script at ./regression/run-test-bucket.
  test:
    name: Test
    runs-on: ubuntu-16.04
    needs: [prepare-riscv-tools-cache, prepare-verilator-cache]
    strategy:
      fail-fast: false
      matrix:
        bucket: [1, 2, 3, 4, 5, 6, 7]
    steps:
      - uses: actions/checkout@v2

      - name: Use riscv-tools Cache
        # TODO: Use v2 once it is released. See the first occurrance of
        # actions/cache in this file for more details.
        uses: actions/cache@9ab95382c899bf0953a0c6c1374373fc40456ffe
        with:
          path: |
            ./regression/install
            ./regression/stamps/rocket-tools_checkout.stamp
          key: riscv-tools-${{ hashFiles('./riscv-tools.hash') }}-v1

      - name: Use Verilator Cache
        # TODO: Use v2 once it is released. See the first occurrance of
        # actions/cache in this file for more details.
        uses: actions/cache@9ab95382c899bf0953a0c6c1374373fc40456ffe
        with:
          path: ./emulator/verilator
          key: verilator-${{ hashFiles('./verilator.hash') }}-v1

      - name: Use SBT Cache
        # TODO: Use v2 once it is released. See the first occurrance of
        # actions/cache in this file for more details.
        uses: actions/cache@9ab95382c899bf0953a0c6c1374373fc40456ffe
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}-v1

      - name: Install Dependencies
        run: |
          sudo apt-get install -y \
            device-tree-compiler \
            g++-4.8 \
            gcc-4.8
          python3 -m pip install pexpect==4.3.1

      - env:
          CXX: g++-4.8
          CC: gcc-4.8
        run: ./regression/run-test-bucket ${{ matrix.bucket }}

      - if: failure()
        name: Upload Artifacts on Failure
        uses: actions/upload-artifact@v1
        with:
          name: test-bucket-${{ matrix.bucket }}-failures
          path: emulator/output
